[2025-01-14T02:41:27.752+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:27.754+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:41:27.756+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:27.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:27.784+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:27.783+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 3
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:41:27.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:27.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.062 seconds
[2025-01-14T02:41:31.784+0000] {processor.py:186} INFO - Started process (PID=256) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:31.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:41:31.787+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:31.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:31.813+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:31.811+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:41:31.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:31.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.062 seconds
[2025-01-14T02:41:35.916+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:35.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:41:35.919+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:35.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:35.946+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:35.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:41:35.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:35.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.058 seconds
[2025-01-14T02:41:37.706+0000] {processor.py:186} INFO - Started process (PID=266) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:37.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:41:37.716+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:37.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:37.774+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:37.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:41:37.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:37.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.101 seconds
[2025-01-14T02:41:37.866+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:37.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:41:37.870+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:37.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:37.900+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:37.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:41:37.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:37.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.062 seconds
[2025-01-14T02:41:37.982+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:37.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:41:37.986+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:37.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:38.019+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:38.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:41:38.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:38.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.065 seconds
[2025-01-14T02:41:38.092+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:38.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:41:38.096+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:38.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:38.117+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:38.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:41:38.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:38.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.050 seconds
[2025-01-14T02:41:38.191+0000] {processor.py:186} INFO - Started process (PID=286) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:38.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:41:38.194+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:38.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:38.239+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:41:38.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:41:38.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:41:38.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.083 seconds
[2025-01-14T02:42:08.673+0000] {processor.py:186} INFO - Started process (PID=297) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:42:08.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:42:08.678+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:42:08.677+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:42:08.707+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:42:08.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:42:08.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:42:08.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.059 seconds
[2025-01-14T02:42:39.248+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:42:39.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:42:39.253+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:42:39.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:42:39.286+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:42:39.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 4
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T02:42:39.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:42:39.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.075 seconds
[2025-01-14T02:43:04.615+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:43:04.623+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:43:04.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.672+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:43:04.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 9
    from airflow.operators
                          ^
SyntaxError: invalid syntax
[2025-01-14T02:43:04.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.087 seconds
[2025-01-14T02:43:04.752+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:43:04.757+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:43:04.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.793+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:43:04.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 9
    from airflow.operators
                          ^
SyntaxError: invalid syntax
[2025-01-14T02:43:04.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.075 seconds
[2025-01-14T02:43:04.876+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:43:04.881+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:43:04.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.912+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:43:04.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 9
    from airflow.operators
                          ^
SyntaxError: invalid syntax
[2025-01-14T02:43:04.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:04.934+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.064 seconds
[2025-01-14T02:43:10.484+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:10.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:43:10.488+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:43:10.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:10.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:10.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.120 seconds
[2025-01-14T02:43:41.015+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:41.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:43:41.038+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:43:41.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:41.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:43:41.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.208 seconds
[2025-01-14T02:44:11.508+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:11.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:44:11.514+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:11.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:11.558+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:11.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.068 seconds
[2025-01-14T02:44:27.821+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:27.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:44:27.825+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:27.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:27.849+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:27.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 12
    from airflow.providers
                          ^
SyntaxError: invalid syntax
[2025-01-14T02:44:27.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:27.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.052 seconds
[2025-01-14T02:44:45.978+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:45.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:44:45.982+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:45.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:46.005+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:46.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 12
    from airflow.providers
                          ^
SyntaxError: invalid syntax
[2025-01-14T02:44:46.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:46.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.049 seconds
[2025-01-14T02:44:59.013+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:59.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:44:59.018+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:59.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:59.082+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:59.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 12, in <module>
    from airflow.providers.aws.operators.s3 import S3CreateBucketOperator
ModuleNotFoundError: No module named 'airflow.providers.aws'
[2025-01-14T02:44:59.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:59.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.102 seconds
[2025-01-14T02:44:59.155+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:59.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:44:59.158+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:59.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:59.178+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:44:59.174+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 12, in <module>
    from airflow.providers.aws.operators.s3 import S3CreateBucketOperator
ModuleNotFoundError: No module named 'airflow.providers.aws'
[2025-01-14T02:44:59.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:44:59.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.070 seconds
[2025-01-14T02:45:03.254+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:03.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:45:03.257+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:45:03.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:03.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:03.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.049 seconds
[2025-01-14T02:45:03.347+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:03.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:45:03.350+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:45:03.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:03.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:03.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.037 seconds
[2025-01-14T02:45:07.465+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:45:07.470+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:45:07.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.504+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.057 seconds
[2025-01-14T02:45:07.566+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:45:07.570+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:45:07.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.050 seconds
[2025-01-14T02:45:07.806+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:45:07.813+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:45:07.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:07.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.056 seconds
[2025-01-14T02:45:37.973+0000] {processor.py:186} INFO - Started process (PID=430) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:37.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:45:37.978+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:45:37.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:38.003+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:45:38.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.055 seconds
[2025-01-14T02:46:08.409+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:08.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:46:08.413+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:46:08.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:08.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:08.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.086 seconds
[2025-01-14T02:46:37.858+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:37.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:46:37.866+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:46:37.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:37.919+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:46:37.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 32
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:46:37.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:37.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.096 seconds
[2025-01-14T02:46:38.022+0000] {processor.py:186} INFO - Started process (PID=457) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:38.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:46:38.026+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:46:38.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:38.105+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:46:38.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 32
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:46:38.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:46:38.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.116 seconds
[2025-01-14T02:47:08.470+0000] {processor.py:186} INFO - Started process (PID=468) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:08.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:47:08.476+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:08.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:08.527+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:08.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 32
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:47:08.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:08.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.094 seconds
[2025-01-14T02:47:13.794+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:13.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:47:13.797+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:13.797+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:13.831+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:13.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 33
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:47:13.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:13.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.067 seconds
[2025-01-14T02:47:15.864+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:15.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:47:15.878+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:15.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:15.916+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:15.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 34
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:47:15.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:15.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.079 seconds
[2025-01-14T02:47:44.476+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:44.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:47:44.481+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:44.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:44.502+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:44.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 34
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:47:44.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:44.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.060 seconds
[2025-01-14T02:47:59.621+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:59.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:47:59.625+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:59.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:59.653+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:47:59.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 37
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:47:59.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:47:59.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.059 seconds
[2025-01-14T02:48:01.760+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:01.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:48:01.764+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:48:01.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:01.785+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:48:01.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 36
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:48:01.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:01.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.059 seconds
[2025-01-14T02:48:17.154+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:17.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:48:17.159+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:48:17.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:17.203+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:48:17.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 37
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:48:17.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:17.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.103 seconds
[2025-01-14T02:48:47.545+0000] {processor.py:186} INFO - Started process (PID=521) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:47.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:48:47.551+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:48:47.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:47.709+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:48:47.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 37
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:48:47.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:48:47.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.196 seconds
[2025-01-14T02:49:18.768+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:49:18.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:49:18.776+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:49:18.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:49:18.821+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:49:18.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 37
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:49:18.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:49:18.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.085 seconds
[2025-01-14T02:49:48.980+0000] {processor.py:186} INFO - Started process (PID=543) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:49:48.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:49:48.983+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:49:48.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:49:49.029+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:49:49.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 37
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:49:49.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:49:49.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.080 seconds
[2025-01-14T02:50:19.488+0000] {processor.py:186} INFO - Started process (PID=554) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:19.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:50:19.493+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:50:19.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:19.530+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:50:19.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 37
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:50:19.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:19.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.083 seconds
[2025-01-14T02:50:49.837+0000] {processor.py:186} INFO - Started process (PID=565) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:49.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:50:49.842+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:50:49.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:49.881+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:50:49.880+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 37
    )
     ^
SyntaxError: expected ':'
[2025-01-14T02:50:49.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:49.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.070 seconds
[2025-01-14T02:50:54.057+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:54.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:50:54.063+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:50:54.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:54.136+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:50:54.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 39, in <module>
    pull_forex_data = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-14T02:50:54.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:50:54.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.108 seconds
[2025-01-14T02:51:10.339+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:10.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:51:10.344+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:10.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:10.470+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:10.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 42, in <module>
    pull_forex_data = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-14T02:51:10.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:10.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.163 seconds
[2025-01-14T02:51:16.237+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:51:16.241+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:16.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.267+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:16.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 42, in <module>
    pull_forex_data = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-14T02:51:16.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.062 seconds
[2025-01-14T02:51:16.359+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:51:16.363+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:16.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.378+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:16.375+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 42, in <module>
    pull_forex_data = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-14T02:51:16.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.043 seconds
[2025-01-14T02:51:16.571+0000] {processor.py:186} INFO - Started process (PID=596) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:51:16.579+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:16.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.633+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:16.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/forex_ml_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/forex_ml_pipeline.py", line 42, in <module>
    pull_forex_data = PythonOperator(
                      ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2025-01-14T02:51:16.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:16.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.097 seconds
[2025-01-14T02:51:33.993+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:33.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:51:33.997+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:33.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:34.073+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:34.272+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.271+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:forex_ml_pipeline
[2025-01-14T02:51:34.283+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.283+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:forex_ml_pipeline
[2025-01-14T02:51:34.292+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.292+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:forex_ml_pipeline
[2025-01-14T02:51:34.305+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.305+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:forex_ml_pipeline
[2025-01-14T02:51:34.318+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.318+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:forex_ml_pipeline
[2025-01-14T02:51:34.331+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.331+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:forex_ml_pipeline
[2025-01-14T02:51:34.340+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.340+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:forex_ml_pipeline
[2025-01-14T02:51:34.341+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.341+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:51:34.355+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.355+0000] {dag.py:3262} INFO - Creating ORM DAG for forex_ml_pipeline
[2025-01-14T02:51:34.368+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:34.367+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2024-01-07 12:00:00+00:00, run_after=2024-01-14 12:00:00+00:00
[2025-01-14T02:51:34.394+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.407 seconds
[2025-01-14T02:51:36.493+0000] {processor.py:186} INFO - Started process (PID=612) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:36.495+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:51:36.499+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:36.499+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:36.566+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:51:36.577+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:36.577+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:51:36.603+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:51:36.603+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2024-01-07 12:00:00+00:00, run_after=2024-01-14 12:00:00+00:00
[2025-01-14T02:51:36.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.141 seconds
[2025-01-14T02:52:06.864+0000] {processor.py:186} INFO - Started process (PID=623) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:06.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:52:06.868+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:06.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:06.929+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:06.950+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:06.949+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:52:06.975+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:06.975+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2024-01-07 12:00:00+00:00, run_after=2024-01-14 12:00:00+00:00
[2025-01-14T02:52:06.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.140 seconds
[2025-01-14T02:52:08.676+0000] {processor.py:186} INFO - Started process (PID=628) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:08.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:52:08.681+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:08.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:08.759+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:08.785+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:08.784+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:52:08.817+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:08.817+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2024-01-07 12:00:00+00:00, run_after=2024-01-14 12:00:00+00:00
[2025-01-14T02:52:08.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.181 seconds
[2025-01-14T02:52:08.901+0000] {processor.py:186} INFO - Started process (PID=633) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:08.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:52:08.906+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:08.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:09.062+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:09.080+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:09.080+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:52:09.099+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:09.099+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2024-01-07 12:00:00+00:00, run_after=2024-01-14 12:00:00+00:00
[2025-01-14T02:52:09.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.229 seconds
[2025-01-14T02:52:40.137+0000] {processor.py:186} INFO - Started process (PID=776) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:40.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:52:40.141+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:40.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:40.168+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:52:40.189+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:40.189+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:52:40.211+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:52:40.211+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2024-11-03 12:00:00+00:00, run_after=2024-11-10 12:00:00+00:00
[2025-01-14T02:52:40.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.100 seconds
[2025-01-14T02:53:10.523+0000] {processor.py:186} INFO - Started process (PID=817) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:53:10.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:53:10.526+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:53:10.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:53:10.548+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:53:10.572+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:53:10.572+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:53:10.593+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:53:10.593+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2025-01-12 12:00:00+00:00, run_after=2025-01-19 12:00:00+00:00
[2025-01-14T02:53:10.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.106 seconds
[2025-01-14T02:53:40.909+0000] {processor.py:186} INFO - Started process (PID=828) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:53:40.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:53:40.913+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:53:40.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:53:40.957+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:53:41.007+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:53:41.007+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:53:41.028+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:53:41.027+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2025-01-12 12:00:00+00:00, run_after=2025-01-19 12:00:00+00:00
[2025-01-14T02:53:41.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.159 seconds
[2025-01-14T02:54:11.352+0000] {processor.py:186} INFO - Started process (PID=839) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:54:11.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:54:11.357+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:54:11.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:54:11.391+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:54:11.410+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:54:11.409+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:54:11.429+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:54:11.429+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2025-01-12 12:00:00+00:00, run_after=2025-01-19 12:00:00+00:00
[2025-01-14T02:54:11.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.109 seconds
[2025-01-14T02:54:42.491+0000] {processor.py:186} INFO - Started process (PID=856) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:54:42.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:54:42.495+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:54:42.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:54:42.513+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:54:42.531+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:54:42.530+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:54:42.550+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:54:42.549+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2025-01-12 12:00:00+00:00, run_after=2025-01-19 12:00:00+00:00
[2025-01-14T02:54:42.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.094 seconds
[2025-01-14T02:55:12.745+0000] {processor.py:186} INFO - Started process (PID=867) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:55:12.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:55:12.750+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:55:12.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:55:12.784+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:55:12.807+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:55:12.807+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:55:12.833+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:55:12.832+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2025-01-12 12:00:00+00:00, run_after=2025-01-19 12:00:00+00:00
[2025-01-14T02:55:12.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.119 seconds
[2025-01-14T02:55:42.993+0000] {processor.py:186} INFO - Started process (PID=878) to work on /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:55:42.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/forex_ml_pipeline.py for tasks to queue
[2025-01-14T02:55:42.997+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:55:42.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:55:43.028+0000] {processor.py:925} INFO - DAG(s) 'forex_ml_pipeline' retrieved from /opt/airflow/dags/forex_ml_pipeline.py
[2025-01-14T02:55:43.047+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:55:43.047+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T02:55:43.069+0000] {logging_mixin.py:190} INFO - [2025-01-14T02:55:43.069+0000] {dag.py:4180} INFO - Setting next_dagrun for forex_ml_pipeline to 2025-01-12 12:00:00+00:00, run_after=2025-01-19 12:00:00+00:00
[2025-01-14T02:55:43.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/forex_ml_pipeline.py took 0.115 seconds
